# Trivy Configuration for Renderowl 2.0
# https://aquasecurity.github.io/trivy/latest/docs/configuration/

# Scan settings
severity:
  - CRITICAL
  - HIGH
  - MEDIUM
  # Uncomment to include LOW severity
  # - LOW
  # Uncomment to include UNKNOWN severity
  # - UNKNOWN

# Vulnerability database
vulnerability:
  type:
    - os
    - library
  # Skip unfixed vulnerabilities
  ignore-unfixed: true

# Ignore patterns
ignorefile: .trivyignore

# Scan targets
scan:
  # Include dev dependencies
  include-dev-deps: false
  # Skip directories
  skip-dirs:
    - ./frontend/node_modules
    - ./frontend/.next
    - ./frontend/dist
    - ./vendor
    - ./tmp
    - ./cache
  # Skip files
  skip-files:
    - "**/*_test.go"
    - "**/*.test.ts"
    - "**/*.test.tsx"

# Report format
format: sarif

# Exit code
exit-code: 1

# Only show vulnerabilities with fixes
ignore-unfixed: true

# Cache settings
cache:
  backend: fs
  dir: $HOME/.cache/trivy

# DB settings
db:
  repository: ghcr.io/aquasecurity/trivy-db
  java-repository: ghcr.io/aquasecurity/trivy-java-db
