package domain

import (
	"encoding/json"
	"time"
)

// TemplateCategory represents template categories
type TemplateCategory string

const (
	CategoryYouTube      TemplateCategory = "youtube"
	CategoryTikTok       TemplateCategory = "tiktok"
	CategoryInstagram    TemplateCategory = "instagram"
	CategoryAds          TemplateCategory = "ads"
	CategoryEducation    TemplateCategory = "education"
	CategorySocial       TemplateCategory = "social"
	CategoryCorporate    TemplateCategory = "corporate"
	CategoryNews         TemplateCategory = "news"
	CategoryStorytelling TemplateCategory = "storytelling"
	CategoryListicle     TemplateCategory = "listicle"
	CategoryExplainer    TemplateCategory = "explainer"
)

// Template represents a video template
type Template struct {
	ID           string          `json:"id"`
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Category     string          `json:"category"`
	Thumbnail    string          `json:"thumbnail"`
	Gradient     string          `json:"gradient"`
	Icon         string          `json:"icon"`
	Duration     float64         `json:"duration"`
	Width        int             `json:"width"`
	Height       int             `json:"height"`
	FPS          int             `json:"fps"`
	Scenes       []TemplateScene `json:"scenes,omitempty"`
	Popularity   int             `json:"popularity"`
	Version      int             `json:"version"`
	IsActive     bool            `json:"isActive"`
	Tags         []string        `json:"tags,omitempty"`
	CreatedAt    time.Time       `json:"createdAt"`
	UpdatedAt    time.Time       `json:"updatedAt"`
}

// TemplateScene represents a scene within a template
type TemplateScene struct {
	ID          string                 `json:"id"`
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	Duration    float64                `json:"duration"`
	Order       int                    `json:"order"`
	Clips       []TemplateClip         `json:"clips,omitempty"`
	Transitions *TemplateTransition    `json:"transitions,omitempty"`
	Settings    map[string]interface{} `json:"settings,omitempty"`
}

// TemplateClip represents a clip configuration in a template scene
type TemplateClip struct {
	ID          string                 `json:"id"`
	Name        string                 `json:"name"`
	Type        string                 `json:"type"` // video, audio, image, text
	SourceType  string                 `json:"sourceType"` // url, placeholder, uploaded
	SourceURL   string                 `json:"sourceUrl,omitempty"`
	Placeholder string                 `json:"placeholder,omitempty"`
	StartTime   float64                `json:"startTime"`
	EndTime     float64                `json:"endTime"`
	PositionX   float64                `json:"positionX"`
	PositionY   float64                `json:"positionY"`
	Scale       float64                `json:"scale"`
	Rotation    float64                `json:"rotation"`
	Opacity     float64                `json:"opacity"`
	TextContent string                 `json:"textContent,omitempty"`
	TextStyle   *TemplateTextStyle     `json:"textStyle,omitempty"`
	Settings    map[string]interface{} `json:"settings,omitempty"`
}

// TemplateTextStyle represents text styling for template clips
type TemplateTextStyle struct {
	FontSize        int     `json:"fontSize"`
	FontFamily      string  `json:"fontFamily"`
	Color           string  `json:"color"`
	Background      string  `json:"background,omitempty"`
	BackgroundColor string  `json:"backgroundColor,omitempty"`
	Bold            bool    `json:"bold"`
	Italic          bool    `json:"italic"`
	Alignment       string  `json:"alignment"`
	LineHeight      float64 `json:"lineHeight,omitempty"`
	LetterSpacing   float64 `json:"letterSpacing,omitempty"`
}

// TemplateTransition represents transition settings
type TemplateTransition struct {
	Type     string  `json:"type"` // fade, slide, zoom, wipe, none
	Duration float64 `json:"duration"`
	Easing   string  `json:"easing,omitempty"`
}

// UseTemplateRequest represents a request to use a template
type UseTemplateRequest struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description,omitempty"`
	CustomData  map[string]interface{} `json:"customData,omitempty"` // For replacing placeholders
}

// UseTemplateResponse represents the response after using a template
type UseTemplateResponse struct {
	TimelineID string    `json:"timelineId"`
	Message    string    `json:"message"`
	TemplateID string    `json:"templateId"`
	CreatedAt  time.Time `json:"createdAt"`
}

// TemplateFilter represents filter options for listing templates
type TemplateFilter struct {
	Category string
	Search   string
	Limit    int
	Offset   int
}

// ScenesJSON is a helper type for JSON serialization
type ScenesJSON []TemplateScene

// Value implements driver.Valuer for database storage
func (s ScenesJSON) Value() (interface{}, error) {
	return json.Marshal(s)
}

// Scan implements sql.Scanner for database retrieval
func (s *ScenesJSON) Scan(value interface{}) error {
	if value == nil {
		*s = ScenesJSON{}
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(bytes, s)
}

// TagsJSON is a helper type for tags JSON serialization
type TagsJSON []string

// Value implements driver.Valuer
func (t TagsJSON) Value() (interface{}, error) {
	return json.Marshal(t)
}

// Scan implements sql.Scanner
func (t *TagsJSON) Scan(value interface{}) error {
	if value == nil {
		*t = TagsJSON{}
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return nil
	}
	return json.Unmarshal(bytes, t)
}

// GetDefaultTemplates returns the built-in default templates
func GetDefaultTemplates() []*Template {
	return []*Template{
		getYouTubeIntroTemplate(),
		getProductDemoTemplate(),
		getEducationalTutorialTemplate(),
		getTikTokShortTemplate(),
		getInstagramReelTemplate(),
		getAdCommercialTemplate(),
		getNewsUpdateTemplate(),
		getStorytellingTemplate(),
		getListicleVideoTemplate(),
		getExplainerVideoTemplate(),
	}
}

// getYouTubeIntroTemplate creates a YouTube intro template
func getYouTubeIntroTemplate() *Template {
	return &Template{
		ID:          "tpl-youtube-intro",
		Name:        "YouTube Intro Pro",
		Description: "Professional intro with animated logo, title cards, and background music. Perfect for establishing your brand.",
		Category:    string(CategoryYouTube),
		Thumbnail:   "🎬",
		Icon:        "🎬",
		Gradient:    "from-red-500 to-pink-600",
		Duration:    8,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  98,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"intro", "youtube", "branding", "logo", "animated"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Logo Reveal",
				Description: "Animated logo with particle effects",
				Duration:    3,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "animated_gradient_background",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-logo",
						Name:        "Your Logo",
						Type:        "image",
						SourceType:  "placeholder",
						Placeholder: "upload_logo",
						StartTime:   0.5,
						EndTime:     2.5,
						PositionX:   0,
						PositionY:   -50,
						Scale:       0.8,
						Opacity:     1,
					},
					{
						ID:          "clip-title",
						Name:        "Channel Name",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_channel_name",
						StartTime:   1,
						EndTime:     3,
						PositionX:   0,
						PositionY:   100,
						Scale:       1,
						Opacity:     1,
						TextContent: "YOUR CHANNEL",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "fade",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-2",
				Name:        "Tagline",
				Description: "Your tagline or slogan",
				Duration:    3,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-tagline",
						Name:        "Tagline Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_tagline",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Creating amazing content",
						TextStyle: &TemplateTextStyle{
							FontSize:   32,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Italic:     true,
							Alignment:  "center",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "fade",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-3",
				Name:        "Subscribe CTA",
				Description: "Call to action for subscribers",
				Duration:    2,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-subscribe",
						Name:        "Subscribe Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "subscribe_cta",
						StartTime:   0,
						EndTime:     2,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Subscribe & Like! 👍",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FF0000",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getProductDemoTemplate creates a product demo template
func getProductDemoTemplate() *Template {
	return &Template{
		ID:          "tpl-product-demo",
		Name:        "Product Demo",
		Description: "Showcase your product with professional shots, feature highlights, and call-to-action.",
		Category:    string(CategoryAds),
		Thumbnail:   "🛍️",
		Icon:        "🛍️",
		Gradient:    "from-blue-500 to-cyan-500",
		Duration:    30,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  92,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"product", "demo", "showcase", "features", "marketing"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Product Reveal",
				Description: "Stunning product reveal shot",
				Duration:    5,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-product",
						Name:        "Product Image",
						Type:        "image",
						SourceType:  "placeholder",
						Placeholder: "upload_product_image",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-product-name",
						Name:        "Product Name",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_product_name",
						StartTime:   1,
						EndTime:     5,
						PositionX:   0,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "PRODUCT NAME",
						TextStyle: &TemplateTextStyle{
							FontSize:   56,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "zoom",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-2",
				Name:        "Feature 1",
				Description: "Highlight first key feature",
				Duration:    6,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-feature-1-icon",
						Name:        "Feature Icon",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "feature_1_icon",
						StartTime:   0,
						EndTime:     6,
						PositionX:   -300,
						PositionY:   -100,
						Scale:       1,
						Opacity:     1,
						TextContent: "✨",
						TextStyle: &TemplateTextStyle{
							FontSize: 72,
							Alignment: "center",
						},
					},
					{
						ID:          "clip-feature-1-title",
						Name:        "Feature Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "feature_1_title",
						StartTime:   0.5,
						EndTime:     6,
						PositionX:   100,
						PositionY:   -80,
						Scale:       1,
						Opacity:     1,
						TextContent: "Amazing Feature",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-feature-1-desc",
						Name:        "Feature Description",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "feature_1_desc",
						StartTime:   1,
						EndTime:     6,
						PositionX:   100,
						PositionY:   20,
						Scale:       1,
						Opacity:     1,
						TextContent: "Describe what makes this feature special",
						TextStyle: &TemplateTextStyle{
							FontSize:   20,
							FontFamily: "Inter",
							Color:      "#CCCCCC",
							Alignment:  "left",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "slide",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-3",
				Name:        "Feature 2",
				Description: "Highlight second key feature",
				Duration:    6,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-feature-2-icon",
						Name:        "Feature Icon",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "feature_2_icon",
						StartTime:   0,
						EndTime:     6,
						PositionX:   -300,
						PositionY:   -100,
						Scale:       1,
						Opacity:     1,
						TextContent: "🚀",
						TextStyle: &TemplateTextStyle{
							FontSize: 72,
							Alignment: "center",
						},
					},
					{
						ID:          "clip-feature-2-title",
						Name:        "Feature Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "feature_2_title",
						StartTime:   0.5,
						EndTime:     6,
						PositionX:   100,
						PositionY:   -80,
						Scale:       1,
						Opacity:     1,
						TextContent: "Fast & Powerful",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "slide",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-4",
				Name:        "Call to Action",
				Description: "Final CTA with pricing or offer",
				Duration:    5,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-offer",
						Name:        "Offer Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "offer_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Get 20% Off Today!",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFD700",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-cta",
						Name:        "CTA Button",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_text",
						StartTime:   1.5,
						EndTime:     5,
						PositionX:   0,
						PositionY:   80,
						Scale:       1,
						Opacity:     1,
						TextContent: "Shop Now →",
						TextStyle: &TemplateTextStyle{
							FontSize:        28,
							FontFamily:      "Inter",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#0066CC",
						},
					},
				},
			},
		},
	}
}

// getEducationalTutorialTemplate creates an educational tutorial template
func getEducationalTutorialTemplate() *Template {
	return &Template{
		ID:          "tpl-education-tutorial",
		Name:        "Educational Tutorial",
		Description: "Clean, focused layout perfect for teaching concepts with on-screen text and annotations.",
		Category:    string(CategoryEducation),
		Thumbnail:   "📚",
		Icon:        "📚",
		Gradient:    "from-green-500 to-teal-500",
		Duration:    60,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  88,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"education", "tutorial", "teaching", "learning", "course"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Title Card",
				Description: "Introduction title",
				Duration:    5,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "gradient_background",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-title",
						Name:        "Tutorial Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_tutorial_title",
						StartTime:   0.5,
						EndTime:     5,
						PositionX:   0,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "How To Get Started",
						TextStyle: &TemplateTextStyle{
							FontSize:   56,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-subtitle",
						Name:        "Subtitle",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_subtitle",
						StartTime:   1.5,
						EndTime:     5,
						PositionX:   0,
						PositionY:   50,
						Scale:       1,
						Opacity:     1,
						TextContent: "A step-by-step guide",
						TextStyle: &TemplateTextStyle{
							FontSize:   24,
							FontFamily: "Inter",
							Color:      "#AAFFAA",
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-2",
				Name:        "Step 1",
				Description: "First instruction step",
				Duration:    12,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-step-number",
						Name:        "Step Number",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_number",
						StartTime:   0,
						EndTime:     12,
						PositionX:   -400,
						PositionY:   -250,
						Scale:       1,
						Opacity:     1,
						TextContent: "01",
						TextStyle: &TemplateTextStyle{
							FontSize:   120,
							FontFamily: "Inter",
							Color:      "#22C55E",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-step-title",
						Name:        "Step Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_title",
						StartTime:   0.5,
						EndTime:     12,
						PositionX:   0,
						PositionY:   -250,
						Scale:       1,
						Opacity:     1,
						TextContent: "Prepare Your Workspace",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-demo-area",
						Name:        "Demo Area",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "screen_recording_placeholder",
						StartTime:   0,
						EndTime:     12,
						PositionX:   0,
						PositionY:   50,
						Scale:       0.8,
						Opacity:     1,
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Step 2",
				Description: "Second instruction step",
				Duration:    12,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-step-number",
						Name:        "Step Number",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_number",
						StartTime:   0,
						EndTime:     12,
						PositionX:   -400,
						PositionY:   -250,
						Scale:       1,
						Opacity:     1,
						TextContent: "02",
						TextStyle: &TemplateTextStyle{
							FontSize:   120,
							FontFamily: "Inter",
							Color:      "#22C55E",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-step-title",
						Name:        "Step Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_title",
						StartTime:   0.5,
						EndTime:     12,
						PositionX:   0,
						PositionY:   -250,
						Scale:       1,
						Opacity:     1,
						TextContent: "Configure Settings",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "Summary",
				Description: "Wrap-up and key takeaways",
				Duration:    8,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-summary-title",
						Name:        "Summary Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "summary_title",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -150,
						Scale:       1,
						Opacity:     1,
						TextContent: "Key Takeaways",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#22C55E",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-takeaway-1",
						Name:        "Takeaway 1",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "takeaway_1",
						StartTime:   1,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -30,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Always start with a plan",
						TextStyle: &TemplateTextStyle{
							FontSize:   28,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-takeaway-2",
						Name:        "Takeaway 2",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "takeaway_2",
						StartTime:   2.5,
						EndTime:     8,
						PositionX:   0,
						PositionY:   40,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Test before you deploy",
						TextStyle: &TemplateTextStyle{
							FontSize:   28,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-takeaway-3",
						Name:        "Takeaway 3",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "takeaway_3",
						StartTime:   4,
						EndTime:     8,
						PositionX:   0,
						PositionY:   110,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Keep learning and improving",
						TextStyle: &TemplateTextStyle{
							FontSize:   28,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-5",
				Name:        "Outro",
				Description: "Call to action for next steps",
				Duration:    8,
				Order:       5,
				Clips: []TemplateClip{
					{
						ID:          "clip-thanks",
						Name:        "Thank You",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "thanks_text",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Thanks for watching!",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-cta",
						Name:        "CTA",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_text",
						StartTime:   2,
						EndTime:     8,
						PositionX:   0,
						PositionY:   50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Subscribe for more tutorials",
						TextStyle: &TemplateTextStyle{
							FontSize:   24,
							FontFamily: "Inter",
							Color:      "#22C55E",
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getTikTokShortTemplate creates a TikTok short-form template
func getTikTokShortTemplate() *Template {
	return &Template{
		ID:          "tpl-tiktok-short",
		Name:        "TikTok Viral Style",
		Description: "Fast-paced, vertical format optimized for TikTok with trending text styles and quick cuts.",
		Category:    string(CategoryTikTok),
		Thumbnail:   "📱",
		Icon:        "📱",
		Gradient:    "from-purple-500 to-pink-500",
		Duration:    15,
		Width:       1080,
		Height:      1920,
		FPS:         30,
		Popularity:  95,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"tiktok", "viral", "short", "vertical", "trending"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Hook",
				Description: "Attention-grabbing hook",
				Duration:    3,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-main",
						Name:        "Main Content",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_main_video",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-hook-text",
						Name:        "Hook Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_hook",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   -350,
						Scale:       1,
						Opacity:     1,
						TextContent: "WAIT FOR IT...",
						TextStyle: &TemplateTextStyle{
							FontSize:   64,
							FontFamily: "Impact",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
							BackgroundColor: "#FF0050",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "zoom",
					Duration: 0.3,
				},
			},
			{
				ID:          "scene-2",
				Name:        "Main Content",
				Description: "Your main video content",
				Duration:    9,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-main",
						Name:        "Main Video",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_main_video",
						StartTime:   0,
						EndTime:     9,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-caption",
						Name:        "Caption",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_caption",
						StartTime:   0,
						EndTime:     9,
						PositionX:   0,
						PositionY:   350,
						Scale:       1,
						Opacity:     1,
						TextContent: "This is INSANE 🤯",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Impact",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
							BackgroundColor: "#000000",
						},
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Outro",
				Description: "Call to action",
				Duration:    3,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-follow",
						Name:        "Follow CTA",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "follow_cta",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Follow for more! 💜",
						TextStyle: &TemplateTextStyle{
							FontSize:   56,
							FontFamily: "Impact",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
							BackgroundColor: "#FF0050",
						},
					},
				},
			},
		},
	}
}

// getInstagramReelTemplate creates an Instagram Reel template
func getInstagramReelTemplate() *Template {
	return &Template{
		ID:          "tpl-instagram-reel",
		Name:        "Instagram Reel",
		Description: "Vertical format with aesthetic transitions and text overlays perfect for Instagram Reels.",
		Category:    string(CategoryInstagram),
		Thumbnail:   "📸",
		Icon:        "📸",
		Gradient:    "from-orange-500 to-pink-500",
		Duration:    15,
		Width:       1080,
		Height:      1920,
		FPS:         30,
		Popularity:  90,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"instagram", "reel", "vertical", "aesthetic", "social"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Opening",
				Description: "Stylish opening shot",
				Duration:    4,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-photo",
						Name:        "Photo/Video",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_content",
						StartTime:   0,
						EndTime:     4,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-title",
						Name:        "Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "enter_title",
						StartTime:   0.5,
						EndTime:     4,
						PositionX:   0,
						PositionY:   -350,
						Scale:       1,
						Opacity:     1,
						TextContent: "POV: Your Aesthetic",
						TextStyle: &TemplateTextStyle{
							FontSize:   52,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Italic:     true,
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.3)",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "fade",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-2",
				Name:        "Main Content",
				Description: "Main visual content",
				Duration:    8,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-main",
						Name:        "Main Content",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_main_content",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Outro",
				Description: "Follow and like CTA",
				Duration:    3,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "gradient_background",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-cta",
						Name:        "CTA",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_text",
						StartTime:   0,
						EndTime:     3,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Follow ✨ Like",
						TextStyle: &TemplateTextStyle{
							FontSize:   56,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getAdCommercialTemplate creates an ad commercial template
func getAdCommercialTemplate() *Template {
	return &Template{
		ID:          "tpl-ad-commercial",
		Name:        "Ad Commercial",
		Description: "Professional 30-second commercial with problem-solution format and strong call-to-action.",
		Category:    string(CategoryAds),
		Thumbnail:   "📺",
		Icon:        "📺",
		Gradient:    "from-indigo-500 to-purple-600",
		Duration:    30,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  87,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"ad", "commercial", "promotion", "marketing", "sales"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Problem",
				Description: "Identify the problem",
				Duration:    5,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-problem",
						Name:        "Problem Visual",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "problem_visual",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-problem-text",
						Name:        "Problem Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "problem_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Tired of [problem]?",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.5)",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "fade",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-2",
				Name:        "Solution Intro",
				Description: "Introduce your solution",
				Duration:    5,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-solution",
						Name:        "Solution Visual",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "solution_visual",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-solution-text",
						Name:        "Solution Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "solution_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Introducing the solution!",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
				Transitions: &TemplateTransition{
					Type:     "slide",
					Duration: 0.5,
				},
			},
			{
				ID:          "scene-3",
				Name:        "Benefits",
				Description: "Showcase key benefits",
				Duration:    12,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-benefit-1",
						Name:        "Benefit 1",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_1",
						StartTime:   0,
						EndTime:     4,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Fast Results",
						TextStyle: &TemplateTextStyle{
							FontSize:   42,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-benefit-2",
						Name:        "Benefit 2",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_2",
						StartTime:   4,
						EndTime:     8,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Easy to Use",
						TextStyle: &TemplateTextStyle{
							FontSize:   42,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-benefit-3",
						Name:        "Benefit 3",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_3",
						StartTime:   8,
						EndTime:     12,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "✓ Affordable Price",
						TextStyle: &TemplateTextStyle{
							FontSize:   42,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "CTA",
				Description: "Strong call-to-action",
				Duration:    8,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-offer",
						Name:        "Offer",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "offer_text",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -80,
						Scale:       1,
						Opacity:     1,
						TextContent: "LIMITED TIME: 50% OFF",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFD700",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-cta-button",
						Name:        "CTA Button",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_button",
						StartTime:   2,
						EndTime:     8,
						PositionX:   0,
						PositionY:   60,
						Scale:       1,
						Opacity:     1,
						TextContent: "ORDER NOW →",
						TextStyle: &TemplateTextStyle{
							FontSize:        36,
							FontFamily:      "Inter",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#6D28D9",
						},
					},
				},
			},
		},
	}
}

// getNewsUpdateTemplate creates a news update template
func getNewsUpdateTemplate() *Template {
	return &Template{
		ID:          "tpl-news-update",
		Name:        "News Update",
		Description: "Professional news format with lower thirds, headlines, and information overlays.",
		Category:    string(CategoryNews),
		Thumbnail:   "📰",
		Icon:        "📰",
		Gradient:    "from-slate-700 to-slate-900",
		Duration:    45,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  85,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"news", "update", "broadcast", "journalism", "information"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Breaking News",
				Description: "Breaking news intro",
				Duration:    5,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "news_background",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-breaking",
						Name:        "Breaking Banner",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "breaking_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   -300,
						Scale:       1,
						Opacity:     1,
						TextContent: "BREAKING NEWS",
						TextStyle: &TemplateTextStyle{
							FontSize:        64,
							FontFamily:      "Impact",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#DC2626",
						},
					},
				},
			},
			{
				ID:          "scene-2",
				Name:        "Headline",
				Description: "Main headline with footage",
				Duration:    15,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-footage",
						Name:        "News Footage",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_footage",
						StartTime:   0,
						EndTime:     15,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-headline",
						Name:        "Headline",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "headline_text",
						StartTime:   0,
						EndTime:     15,
						PositionX:   0,
						PositionY:   350,
						Scale:       1,
						Opacity:     1,
						TextContent: "MAJOR DEVELOPMENT IN [TOPIC]",
						TextStyle: &TemplateTextStyle{
							FontSize:        36,
							FontFamily:      "Inter",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "rgba(0,0,0,0.8)",
						},
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Details",
				Description: "More details and information",
				Duration:    20,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-reporter",
						Name:        "Reporter",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_reporter",
						StartTime:   0,
						EndTime:     20,
						PositionX:   -200,
						PositionY:   0,
						Scale:       0.7,
						Opacity:     1,
					},
					{
						ID:          "clip-lower-third",
						Name:        "Reporter Name",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "reporter_name",
						StartTime:   0,
						EndTime:     20,
						PositionX:   -200,
						PositionY:   280,
						Scale:       1,
						Opacity:     1,
						TextContent: "Jane Smith | Reporter",
						TextStyle: &TemplateTextStyle{
							FontSize:        20,
							FontFamily:      "Inter",
							Color:           "#FFFFFF",
							Alignment:         "center",
							BackgroundColor: "#1E40AF",
						},
					},
					{
						ID:          "clip-details",
						Name:        "Details Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "details_text",
						StartTime:   1,
						EndTime:     20,
						PositionX:   300,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Key details about\nthe story here...",
						TextStyle: &TemplateTextStyle{
							FontSize:   28,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "Outro",
				Description: "Closing and source attribution",
				Duration:    5,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-source",
						Name:        "Source",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "source_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Source: [Your Source]",
						TextStyle: &TemplateTextStyle{
							FontSize:   24,
							FontFamily: "Inter",
							Color:      "#9CA3AF",
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getStorytellingTemplate creates a storytelling template
func getStorytellingTemplate() *Template {
	return &Template{
		ID:          "tpl-storytelling",
		Name:        "Storytelling",
		Description: "Narrative-driven template perfect for sharing stories, experiences, and personal journeys.",
		Category:    string(CategoryStorytelling),
		Thumbnail:   "📖",
		Icon:        "📖",
		Gradient:    "from-amber-600 to-orange-700",
		Duration:    90,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  89,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"story", "narrative", "personal", "journey", "experience"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Opening",
				Description: "Story opening hook",
				Duration:    10,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-opening-visual",
						Name:        "Opening Visual",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_opening",
						StartTime:   0,
						EndTime:     10,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-opening-text",
						Name:        "Opening Line",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "opening_line",
						StartTime:   2,
						EndTime:     10,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "It all started when...",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Italic:     true,
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.4)",
						},
					},
				},
			},
			{
				ID:          "scene-2",
				Name:        "The Journey",
				Description: "Main story progression",
				Duration:    45,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-story-content",
						Name:        "Story Visuals",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_story_content",
						StartTime:   0,
						EndTime:     45,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-chapter-1",
						Name:        "Chapter 1",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "chapter_1",
						StartTime:   5,
						EndTime:     15,
						PositionX:   0,
						PositionY:   350,
						Scale:       1,
						Opacity:     1,
						TextContent: "The Beginning",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.6)",
						},
					},
					{
						ID:          "clip-chapter-2",
						Name:        "Chapter 2",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "chapter_2",
						StartTime:   20,
						EndTime:     30,
						PositionX:   0,
						PositionY:   350,
						Scale:       1,
						Opacity:     1,
						TextContent: "The Challenge",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.6)",
						},
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Resolution",
				Description: "Story conclusion",
				Duration:    20,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-resolution",
						Name:        "Resolution Visual",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_resolution",
						StartTime:   0,
						EndTime:     20,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-moral",
						Name:        "Lesson Learned",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "lesson_text",
						StartTime:   5,
						EndTime:     20,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "And that's when I learned...",
						TextStyle: &TemplateTextStyle{
							FontSize:   42,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Italic:     true,
							Alignment:  "center",
							BackgroundColor: "rgba(0,0,0,0.5)",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "Outro",
				Description: "Closing thoughts",
				Duration:    15,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-closing",
						Name:        "Closing Visual",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "upload_closing",
						StartTime:   0,
						EndTime:     15,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-thanks",
						Name:        "Thank You",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "thanks_text",
						StartTime:   3,
						EndTime:     15,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Thanks for listening to my story",
						TextStyle: &TemplateTextStyle{
							FontSize:   40,
							FontFamily: "Playfair Display",
							Color:      "#FFFFFF",
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getListicleVideoTemplate creates a listicle video template
func getListicleVideoTemplate() *Template {
	return &Template{
		ID:          "tpl-listicle",
		Name:        "Listicle Video",
		Description: "Top 5/10 list format perfect for countdowns, tips, recommendations, and rankings.",
		Category:    string(CategoryListicle),
		Thumbnail:   "📝",
		Icon:        "📝",
		Gradient:    "from-violet-500 to-fuchsia-600",
		Duration:    75,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  91,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"list", "top", "countdown", "tips", "ranking"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Intro",
				Description: "List introduction",
				Duration:    8,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "gradient_background",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-title",
						Name:        "List Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "list_title",
						StartTime:   0.5,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -80,
						Scale:       1,
						Opacity:     1,
						TextContent: "Top 5 Ways to...",
						TextStyle: &TemplateTextStyle{
							FontSize:   56,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-subtitle",
						Name:        "Subtitle",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "list_subtitle",
						StartTime:   2,
						EndTime:     8,
						PositionX:   0,
						PositionY:   20,
						Scale:       1,
						Opacity:     1,
						TextContent: "You won't believe #3!",
						TextStyle: &TemplateTextStyle{
							FontSize:   28,
							FontFamily: "Inter",
							Color:      "#E9D5FF",
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-2",
				Name:        "Item 5",
				Description: "Fifth item",
				Duration:    12,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-number-5",
						Name:        "Number 5",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "number_5",
						StartTime:   0,
						EndTime:     12,
						PositionX:   -400,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "5",
						TextStyle: &TemplateTextStyle{
							FontSize:        120,
							FontFamily:      "Impact",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#8B5CF6",
						},
					},
					{
						ID:          "clip-item-5-title",
						Name:        "Item 5 Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "item_5_title",
						StartTime:   0.5,
						EndTime:     12,
						PositionX:   100,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "First Tip Title",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-item-5-desc",
						Name:        "Item 5 Description",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "item_5_desc",
						StartTime:   1.5,
						EndTime:     12,
						PositionX:   100,
						PositionY:   -100,
						Scale:       1,
						Opacity:     1,
						TextContent: "Description of the first tip goes here",
						TextStyle: &TemplateTextStyle{
							FontSize:   22,
							FontFamily: "Inter",
							Color:      "#DDD6FE",
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "Item 4",
				Description: "Fourth item",
				Duration:    12,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-number-4",
						Name:        "Number 4",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "number_4",
						StartTime:   0,
						EndTime:     12,
						PositionX:   -400,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "4",
						TextStyle: &TemplateTextStyle{
							FontSize:        120,
							FontFamily:      "Impact",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#7C3AED",
						},
					},
					{
						ID:          "clip-item-4-title",
						Name:        "Item 4 Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "item_4_title",
						StartTime:   0.5,
						EndTime:     12,
						PositionX:   100,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "Second Tip Title",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "Item 3",
				Description: "Third item - the highlight",
				Duration:    15,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-number-3",
						Name:        "Number 3",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "number_3",
						StartTime:   0,
						EndTime:     15,
						PositionX:   -400,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "3",
						TextStyle: &TemplateTextStyle{
							FontSize:        140,
							FontFamily:      "Impact",
							Color:           "#FFD700",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#FF0050",
						},
					},
					{
						ID:          "clip-item-3-title",
						Name:        "Item 3 Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "item_3_title",
						StartTime:   0.5,
						EndTime:     15,
						PositionX:   100,
						PositionY:   -200,
						Scale:       1,
						Opacity:     1,
						TextContent: "THE BEST TIP! ✨",
						TextStyle: &TemplateTextStyle{
							FontSize:   42,
							FontFamily: "Inter",
							Color:      "#FFD700",
							Bold:       true,
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-5",
				Name:        "Outro",
				Description: "Closing and CTA",
				Duration:    8,
				Order:       5,
				Clips: []TemplateClip{
					{
						ID:          "clip-question",
						Name:        "Question",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "question_text",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "What's your favorite tip?",
						TextStyle: &TemplateTextStyle{
							FontSize:   44,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-cta",
						Name:        "CTA",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "list_cta",
						StartTime:   3,
						EndTime:     8,
						PositionX:   0,
						PositionY:   60,
						Scale:       1,
						Opacity:     1,
						TextContent: "Comment below! 👇",
						TextStyle: &TemplateTextStyle{
							FontSize:   32,
							FontFamily: "Inter",
							Color:      "#E9D5FF",
							Alignment:  "center",
						},
					},
				},
			},
		},
	}
}

// getExplainerVideoTemplate creates an explainer video template
func getExplainerVideoTemplate() *Template {
	return &Template{
		ID:          "tpl-explainer",
		Name:        "Explainer Video",
		Description: "Clean, animated explainer perfect for introducing concepts, services, or how things work.",
		Category:    string(CategoryExplainer),
		Thumbnail:   "💡",
		Icon:        "💡",
		Gradient:    "from-cyan-500 to-blue-600",
		Duration:    60,
		Width:       1920,
		Height:      1080,
		FPS:         30,
		Popularity:  93,
		Version:     1,
		IsActive:    true,
		Tags:        []string{"explainer", "how-it-works", "introduction", "concept", "service"},
		Scenes: []TemplateScene{
			{
				ID:          "scene-1",
				Name:        "Hook",
				Description: "Grab attention with a question or statement",
				Duration:    5,
				Order:       1,
				Clips: []TemplateClip{
					{
						ID:          "clip-bg",
						Name:        "Background",
						Type:        "video",
						SourceType:  "placeholder",
						Placeholder: "gradient_background",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
					},
					{
						ID:          "clip-hook",
						Name:        "Hook Question",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "hook_question",
						StartTime:   0.5,
						EndTime:     5,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "Ever wondered how...?",
						TextStyle: &TemplateTextStyle{
							FontSize:   48,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-2",
				Name:        "The Problem",
				Description: "Describe the problem",
				Duration:    10,
				Order:       2,
				Clips: []TemplateClip{
					{
						ID:          "clip-problem-icon",
						Name:        "Problem Icon",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "problem_icon",
						StartTime:   0,
						EndTime:     10,
						PositionX:   -350,
						PositionY:   -150,
						Scale:       1,
						Opacity:     1,
						TextContent: "😫",
						TextStyle: &TemplateTextStyle{
							FontSize: 120,
							Alignment: "center",
						},
					},
					{
						ID:          "clip-problem-title",
						Name:        "Problem Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "problem_title",
						StartTime:   0.5,
						EndTime:     10,
						PositionX:   50,
						PositionY:   -150,
						Scale:       1,
						Opacity:     1,
						TextContent: "The Problem",
						TextStyle: &TemplateTextStyle{
							FontSize:   40,
							FontFamily: "Inter",
							Color:      "#FF6B6B",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-problem-desc",
						Name:        "Problem Description",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "problem_desc",
						StartTime:   1.5,
						EndTime:     10,
						PositionX:   50,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Here's what people struggle with...",
						TextStyle: &TemplateTextStyle{
							FontSize:   24,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-3",
				Name:        "The Solution",
				Description: "Present your solution",
				Duration:    12,
				Order:       3,
				Clips: []TemplateClip{
					{
						ID:          "clip-solution-icon",
						Name:        "Solution Icon",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "solution_icon",
						StartTime:   0,
						EndTime:     12,
						PositionX:   -350,
						PositionY:   -150,
						Scale:       1,
						Opacity:     1,
						TextContent: "✨",
						TextStyle: &TemplateTextStyle{
							FontSize: 120,
							Alignment: "center",
						},
					},
					{
						ID:          "clip-solution-title",
						Name:        "Solution Title",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "solution_title",
						StartTime:   0.5,
						EndTime:     12,
						PositionX:   50,
						PositionY:   -150,
						Scale:       1,
						Opacity:     1,
						TextContent: "The Solution",
						TextStyle: &TemplateTextStyle{
							FontSize:   40,
							FontFamily: "Inter",
							Color:      "#4ADE80",
							Bold:       true,
							Alignment:  "left",
						},
					},
					{
						ID:          "clip-solution-desc",
						Name:        "Solution Description",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "solution_desc",
						StartTime:   1.5,
						EndTime:     12,
						PositionX:   50,
						PositionY:   -50,
						Scale:       1,
						Opacity:     1,
						TextContent: "Here's how we solve it...",
						TextStyle: &TemplateTextStyle{
							FontSize:   24,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Alignment:  "left",
						},
					},
				},
			},
			{
				ID:          "scene-4",
				Name:        "How It Works",
				Description: "Step by step explanation",
				Duration:    20,
				Order:       4,
				Clips: []TemplateClip{
					{
						ID:          "clip-step-1",
						Name:        "Step 1",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_1",
						StartTime:   0,
						EndTime:     6,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "1️⃣ Step One: Sign up",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-step-2",
						Name:        "Step 2",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_2",
						StartTime:   7,
						EndTime:     13,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "2️⃣ Step Two: Customize",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-step-3",
						Name:        "Step 3",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "step_3",
						StartTime:   14,
						EndTime:     20,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "3️⃣ Step Three: Enjoy!",
						TextStyle: &TemplateTextStyle{
							FontSize:   36,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-5",
				Name:        "Benefits",
				Description: "Key benefits summary",
				Duration:    8,
				Order:       5,
				Clips: []TemplateClip{
					{
						ID:          "clip-benefit-1",
						Name:        "Benefit 1",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_1",
						StartTime:   0,
						EndTime:     8,
						PositionX:   -300,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "⚡ Fast",
						TextStyle: &TemplateTextStyle{
							FontSize:   32,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-benefit-2",
						Name:        "Benefit 2",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_2",
						StartTime:   0,
						EndTime:     8,
						PositionX:   0,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "🔒 Secure",
						TextStyle: &TemplateTextStyle{
							FontSize:   32,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-benefit-3",
						Name:        "Benefit 3",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "benefit_3",
						StartTime:   0,
						EndTime:     8,
						PositionX:   300,
						PositionY:   0,
						Scale:       1,
						Opacity:     1,
						TextContent: "💰 Affordable",
						TextStyle: &TemplateTextStyle{
							FontSize:   32,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
				},
			},
			{
				ID:          "scene-6",
				Name:        "CTA",
				Description: "Call to action",
				Duration:    5,
				Order:       6,
				Clips: []TemplateClip{
					{
						ID:          "clip-cta-text",
						Name:        "CTA Text",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_text",
						StartTime:   0,
						EndTime:     5,
						PositionX:   0,
						PositionY:   -30,
						Scale:       1,
						Opacity:     1,
						TextContent: "Ready to get started?",
						TextStyle: &TemplateTextStyle{
							FontSize:   44,
							FontFamily: "Inter",
							Color:      "#FFFFFF",
							Bold:       true,
							Alignment:  "center",
						},
					},
					{
						ID:          "clip-cta-button",
						Name:        "CTA Button",
						Type:        "text",
						SourceType:  "placeholder",
						Placeholder: "cta_button",
						StartTime:   1.5,
						EndTime:     5,
						PositionX:   0,
						PositionY:   60,
						Scale:       1,
						Opacity:     1,
						TextContent: "Get Started Today →",
						TextStyle: &TemplateTextStyle{
							FontSize:        28,
							FontFamily:      "Inter",
							Color:           "#FFFFFF",
							Bold:            true,
							Alignment:         "center",
							BackgroundColor: "#2563EB",
						},
					},
				},
			},
		},
	}
}
